### ISSUE TITLE
403 Forbidden: portchecker does not auth with QBitTorrent

### ISSUE THREAD

**Issue by GamingLiamStudios** [TechClusterHQ/qbt-portchecker#2]
As stated in [the docs](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#general-information)
> All API methods require [authentication](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#authentication) (except /api/v2/auth/login, obviously).

This causes any interaction with qbit to return a 403 Forbidden.
To fix all that would need to be done is allowing qbit login info at script start and storing the login cookie between requests, as also demonstrated on the qbit api docs.

**Comment by TechClusterHQ** [comment]
The first paragraph in the "Installation" section of the README describes that you need to enable the "Bypass authentication for clients on localhost" in your qBittorrent settings. This setting disables the need to authenticate when the request is coming from localhost (which is the case when running a docker mod).

**Comment by TechClusterHQ** [comment]
If you have a reason to keep that setting turned off I could look into optionally adding the login cookies to the requests, just let me know 🙂

**Comment by GamingLiamStudios** [comment]
completely missed that one :p

**Comment by TechClusterHQ** [comment]
all good!
